name: Metrics
on:
  schedule:
    - cron: '0 5 * * *'
  
  # Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          user: ieroboticsclub
          commits_authoring: ieroboticsclub
          config_timezone: Europe/Madrid
          template: classic

          base: activity
          base_indepth: yes
          repositories: 1000
          repositories_batch: 2
          repositories_affiliations: owner, collaborator, organization_member
          
          plugin_repositories: yes
          
          
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          
          
          plugin_languages: yes
          plugin_languages_details: percentage, lines
          plugin_languages_indepth: no
          plugin_languages_sections: recently-used
          plugin_languages_analysis_timeout: 60
          plugin_languages_recent_categories: programming, markup, prose
          plugin_languages_recent_load: 5000
          plugin_languages_recent_days: 90
          
          
          
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: chartist
          
          

          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, member, maintainer, scripter, infographile
          plugin_achievements_display: detailed
